using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace StudyTracker.Models.EFModels;

public class AudioMessage
{
    public int AudioMessageId { get; set; }   // Auto-generated by DB
    [Required]
    public string FilePath { get; set; } = "";
    [Required]
    public Category Category { get; set; }
    [Required]
    public int OwnerId { get; set; }          // FK (int instead of Guid)
    [JsonIgnore]
    public AudioOwner? Owner { get; set; }     // Navigation property
}

public enum Category
{
    Little, 
    Good, 
    Exceptional
}